(() => {
  if ("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(() => {});
  const P=window.AirFerryLiteProtocol, video=document.getElementById("video"),canvas=document.getElementById("scanCanvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});
  const startBtn=document.getElementById("startBtn"),stopBtn=document.getElementById("stopBtn"),resetBtn=document.getElementById("resetBtn"),copyMissing=document.getElementById("copyMissing"),status=document.getElementById("status"),fileName=document.getElementById("fileName"),progressText=document.getElementById("progressText"),progressBar=document.getElementById("progressBar"),missingEl=document.getElementById("missing"),hint=document.getElementById("cameraHint"),result=document.getElementById("result"),resultInfo=document.getElementById("resultInfo"),download=document.getElementById("download");
  let stream=null,raf=0,meta=null,chunks=new Map(),lastSize=0,lastMissing=[];
  startBtn.onclick=start;stopBtn.onclick=stop;resetBtn.onclick=reset;copyMissing.onclick=()=>navigator.clipboard?.writeText(lastMissing.join(","));
  async function start(){
    if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();hint.classList.add("hidden");startBtn.disabled=true;stopBtn.disabled=false;status.textContent="正在扫描";scan()}catch(err){status.textContent=err.name==="NotAllowedError"?"摄像头权限被拒绝":"摄像头不可用";hint.textContent="请在 HTTPS 页面中允许摄像头权限"}}
  function stop(){if(!stream)return;stream.getTracks().forEach(t=>t.stop());stream=null;cancelAnimationFrame(raf);startBtn.disabled=false;stopBtn.disabled=true;status.textContent=meta?"已暂停":"等待开始"}
  function reset(){stop();meta=null;chunks=new Map();lastMissing=[];lastSize=0;fileName.textContent="—";progressText.textContent="0%";progressBar.style.width="0%";missingEl.textContent="—";copyMissing.disabled=true;result.hidden=true;status.textContent="等待开始"}
  function scan(){
    if(!stream)return;if(video.readyState>=2){const w=video.videoWidth,h=video.videoHeight;if(w&&h){canvas.width=w;canvas.height=h;ctx.drawImage(video,0,0,w,h);const image=ctx.getImageData(0,0,w,h);const code=jsQR(image.data,w,h,{inversionAttempts:"attemptBoth"});if(code?.data)accept(code.data)}}raf=setTimeout(()=>requestAnimationFrame(scan),70)
  }
  function accept(text){const frame=P.parseFrame(text);if(!frame)return;if(frame.kind==="header"){if(!meta||meta.session!==frame.session){meta=frame;chunks=new Map();result.hidden=true;fileName.textContent=frame.name;status.textContent="已识别文件描述"}return}if(!meta||frame.session!==meta.session||frame.total!==meta.total||frame.index<0||frame.index>=meta.total)return;if(P.crc32(frame.bytes)!==frame.chunkCrc)return;if(!chunks.has(frame.index))chunks.set(frame.index,frame.bytes);update();if(chunks.size===meta.total)finish()}
  function update(){const percent=Math.floor(chunks.size/meta.total*100);progressText.textContent=`${percent}% (${chunks.size}/${meta.total})`;progressBar.style.width=`${percent}%`;lastMissing=[];for(let i=0;i<meta.total;i++)if(!chunks.has(i))lastMissing.push(i);missingEl.textContent=lastMissing.length?lastMissing.slice(0,80).join(", ")+(lastMissing.length>80?" …":""):"全部片段已收到";copyMissing.disabled=!lastMissing.length;status.textContent=chunks.size===meta.total?"正在校验":"接收中"}
  function finish(){if(!result.hidden)return;const bytes=new Uint8Array(meta.size);let offset=0;for(let i=0;i<meta.total;i++){bytes.set(chunks.get(i),offset);offset+=chunks.get(i).length}if(offset!==meta.size||P.crc32(bytes)!==meta.fileCrc){status.textContent="校验失败，请继续扫描";return}const blob=new Blob([bytes],{type:meta.mime});if(download.href)URL.revokeObjectURL(download.href);download.href=URL.createObjectURL(blob);download.download=meta.name;resultInfo.textContent=`${formatBytes(bytes.length)} · CRC-32 校验通过`;result.hidden=false;status.textContent="接收完成"}
  function formatBytes(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
})();
